version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - "./src/:/app/"
      - "/app/node_modules"
    ports:
      - "3000:3000"
    command: npm run dev

volumes:
  node_modules:
    driver: local
